## Numpy Datatypes and Attributes

In [24]:
import numpy as np
import pandas as pd
#shift tab for seeing documentation   esc+X for cut

In [4]:
#main datatype- ndarray
a1=np.array([1,2,3])
a_copy=a1.copy()
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18.0]]])
a1,a2,a3,a_copy,a1[:]

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],
 
        [[ 7.,  8.,  9.],
         [10., 11., 12.]],
 
        [[13., 14., 15.],
         [16., 17., 18.]]]),
 array([1, 2, 3]),
 array([1, 2, 3]))

In [4]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [5]:
a3.shape,a2.shape,a3.shape

((3, 2, 3), (2, 3), (3, 2, 3))

In [6]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [7]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [8]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [9]:
#dataframe from numpy array
df=pd.DataFrame(a2)
df

,0,1,2
0,1,2,3
1,4,5,6


In [10]:
ones=np.ones((2,3))
ones,ones.dtype,type(ones)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 dtype('float64'),
 numpy.ndarray)

In [11]:
zeros=np.zeros((2,3))
zeros,zeros.dtype,type(zeros)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 dtype('float64'),
 numpy.ndarray)

In [12]:
arange=np.arange(0,10,2)
arange

array([0, 2, 4, 6, 8])

In [17]:
#low inclusive and high exclusive
random=np.random.randint(0,10,size=(5,3))
random,random.shape
#random=np.random.randint(10,size=(3,4))

(array([[6, 6, 4],
        [5, 6, 1],
        [1, 4, 6],
        [7, 0, 9],
        [7, 7, 0]]),
 (5, 3))

In [14]:
#(0.0,1.0)
random1=np.random.random((3,4))
random1

array([[0.9316564 , 0.50957204, 0.1153079 , 0.16449508],
       [0.87590344, 0.95829277, 0.25795148, 0.00541591],
       [0.66976788, 0.85551599, 0.51820742, 0.84048816]])

In [15]:
# rand uniform distribution
# randn gaussion or normal distribution

random2=np.random.rand(3,4)
random4=np.random.randn(3,4)
#random values in given shape
random2,random4,random4>0.2

(array([[0.61005502, 0.37358612, 0.54420678, 0.41750238],
        [0.88727671, 0.2310293 , 0.76981266, 0.44036608],
        [0.56969784, 0.56039212, 0.35721218, 0.6546453 ]]),
 array([[ 0.0883564 ,  0.33916554,  0.99710762, -0.77735949],
        [ 0.23431796,  0.61578504, -2.39081875,  1.063484  ],
        [-0.17309241,  0.66034589,  0.32784888, -0.06269007]]),
 array([[False,  True,  True, False],
        [ True,  True, False,  True],
        [False,  True,  True, False]]))

In [29]:
#pseudo-random numbers
np.random.seed(seed=0) #to get same result
random3=np.random.randint(0,10,size=(5,3))
random3,random3.shape

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 (5, 3))

In [32]:
np.random.seed(7)
random4=np.random.random((5,3))
random4,random4.shape

(array([[0.07630829, 0.77991879, 0.43840923],
        [0.72346518, 0.97798951, 0.53849587],
        [0.50112046, 0.07205113, 0.26843898],
        [0.4998825 , 0.67923   , 0.80373904],
        [0.38094113, 0.06593635, 0.2881456 ]]),
 (5, 3))

In [17]:
np.linspace(0,100,30)
# in linspace both are inclusive 0 and 100 and evenly spaced

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [7]:
arange=np.arange(11,20)
arange

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
arrange=np.arange(1,101).reshape(10,10)
arrange[8:,0:3] #last 2 rows and first 3 column values index & selection technique¶

array([[81, 82, 83],
       [91, 92, 93]])

In [21]:
arrange[:,2] #coloumn

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [22]:
arrange[2,:] #row

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
arrange[(1,3),:] #values from the 2nd & 4th rows 

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

an array of all even integers from 2 to 10 and array of all even integers from 22 to 30

2 arrays as rows and create a matrix

In [9]:
b1 = np.arange(2,11,2)
b2= np.arange(22,31,2)
np.stack((b1,b2))

# tuples (b1,b2)

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

2 arrays as columns and create a matrix

In [10]:
np.column_stack((b1,b2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [11]:
array_matrix = np.arange(30).reshape(5,6)
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

 identity matrix of shape 10x10 and replace the 0's with the value 5

In [13]:
eye = np.eye(10)
eye[eye == 0] = 6
eye

array([[1., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 1., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 1., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 1., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 1., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 1., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 1., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 1., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 1., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 1.]])

In [1]:
np.eye(3,3)
np.identity(3)

NameError: name 'np' is not defined

## View Arrays and Matrices

In [40]:
np.unique(random3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a3[0]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
a2[:2],a3[:,:,:1]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1.],
         [ 4.]],
 
        [[ 7.],
         [10.]],
 
        [[13.],
         [16.]]]))

In [43]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [44]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [49]:
a4[:,:,:1,:4],a4[:,:,:,:1]

(array([[[[3, 5, 8, 8]],
 
         [[1, 0, 0, 6]],
 
         [[4, 3, 1, 9]]],
 
 
        [[[3, 0, 4, 8]],
 
         [[9, 9, 0, 6]],
 
         [[7, 5, 4, 9]]]]),
 array([[[[3],
          [5],
          [9],
          [3]],
 
         [[1],
          [7],
          [7],
          [3]],
 
         [[4],
          [9],
          [2],
          [9]]],
 
 
        [[[3],
          [7],
          [6],
          [7]],
 
         [[9],
          [6],
          [6],
          [9]],
 
         [[7],
          [8],
          [3],
          [7]]]]))

## Manipulating Arrays

In [66]:
a=np.array([1,2,3])
b=np.ones(3)
a+b,a-b,a*b,a/b, np.add(a,b), a/2

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([2., 3., 4.]),
 array([0.5, 1. , 1.5]))

In [61]:
c=np.array([[1,2,3],[4,5,6]])
a*c, a/c, a//c #floor 

(array([[ 1,  4,  9],
        [ 4, 10, 18]]),
 array([[1.  , 1.  , 1.  ],
        [0.25, 0.4 , 0.5 ]]),
 array([[1, 1, 1],
        [0, 0, 0]]))

In [58]:
#reshape a2 compatible with a3
#a2 * a3

In [67]:
# a2**2
np.square(a2), np.exp(a2), np.log(a2)

(array([[ 1,  4,  9],
        [16, 25, 36]]),
 array([[  2.71828183,   7.3890561 ,  20.08553692],
        [ 54.59815003, 148.4131591 , 403.42879349]]),
 array([[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]]))

## Aggregation
Aggregation = performing the same operation on a no of things

python methods - python datatypes - sum()

Numpy arrays - np.sum()


In [70]:
l=[1,2,3]
type(l),sum(l),type(a1),sum(a1),np.sum(a1)

(list, 6, numpy.ndarray, 6, 6)

In [72]:
a=np.random.random(100)
a.size,a

(100,
 array([0.03962857, 0.98863433, 0.81874499, 0.63650234, 0.76108474,
        0.18802993, 0.30765459, 0.24639364, 0.59604912, 0.09190485,
        0.89560999, 0.46227594, 0.44481236, 0.1047113 , 0.68490404,
        0.81689399, 0.62955017, 0.24202261, 0.78542072, 0.14567943,
        0.82727633, 0.58070537, 0.28937281, 0.5132434 , 0.6288514 ,
        0.2585895 , 0.84690656, 0.42125371, 0.89233746, 0.83546856,
        0.09934751, 0.64625411, 0.31049457, 0.7540532 , 0.54263166,
        0.45759887, 0.89536678, 0.05725356, 0.55731763, 0.3279111 ,
        0.03527334, 0.75351852, 0.56174066, 0.89414534, 0.59826123,
        0.33703428, 0.98521966, 0.11571405, 0.05260174, 0.73262191,
        0.3708749 , 0.36146508, 0.87653216, 0.32729365, 0.8889886 ,
        0.64398798, 0.32904954, 0.05953265, 0.24510935, 0.9684132 ,
        0.40526764, 0.16003346, 0.29801325, 0.89957578, 0.16497672,
        0.77786007, 0.13486463, 0.96139371, 0.53020539, 0.04316994,
        0.93095468, 0.35822554, 0.73142128

In [74]:
%timeit sum(a)
%timeit np.sum(a) # faster

28.1 µs ± 793 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
7.28 µs ± 28.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
np.mean(a2),np.max(a2),np.min(a2),np.std(a2),np.var(a2)
#variance is measure of avg degree to which each no is different to the mean
#Higher variance= wider range of nos
#Lower variance=lower range of nos

#SD - measure of how spread out a group of nos is from the mean
# SD= np.sqrt(np.var(a2))

(3.5, 6, 1, 1.707825127659933, 2.9166666666666665)